### ISSUE TITLE
Random Int

### ISSUE THREAD

**Issue by tkellehe** [tkellehe/noodel#121]
Look into making the random int actually select each integer equally likely.

**Comment by somebody1234** [comment]
I think `random_int` should call `random(min, max + 1)`

**Comment by tkellehe** [comment]
I totally forgot about! Thanks:) I can't believe you actually read through that crappy code?

**Comment by tkellehe** [comment]
I think instead I will do the `+1` in the code where the random command is interpreted. Thanks:)
